# Generated by Django 3.2.3 on 2021-05-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('connection', models.CharField(default='DEFAULT VALUE', max_length=100)),
            ],
            options={
                'db_table': 'connections',
            },
        ),
    ]
